#ifndef ADDBOOKS_H
#define ADDBOOKS_H

#include <QDialog>
#include "ui_addbooks.h"

namespace Ui {
class AddBooks;
}

/**
 * @class AddBooks
 * @brief Dialog window for adding new books to the system.
 *
 * The AddBooks class provides a user interface that allows
 * users to enter book details and save them to the system.
 * It handles UI interactions such as saving data, clearing fields,
 * loading category suggestions, and navigating back.
 */
class AddBooks : public QDialog
{
    Q_OBJECT

public:

    /**
     * @brief Constructs the AddBooks dialog.
     *
     * @param parent Pointer to the parent widget (default is nullptr).
     */
    explicit AddBooks(QWidget *parent = nullptr);

    /**
     * @brief Destroys the AddBooks dialog.
     *
     * Cleans up allocated UI resources.
     */
    ~AddBooks();

private slots:

    /**
     * @brief Handles the "Go Back" button click event.
     *
     * Closes the dialog and returns to the previous window.
     */
    void on_goBackButton_clicked();

    /**
     * @brief Handles the "Save" button click event.
     *
     * Validates input fields and attempts to save the new book
     * to the database.
     */
    void on_saveButton_clicked();

    /**
     * @brief Handles the "Cancel" button click event.
     *
     * Clears input fields or closes the dialog without saving.
     */
    void on_cancelButton_clicked();

private:

    /**
     * @brief Pointer to the UI components generated by Qt Designer.
     */
    Ui::AddBooks *ui;

    /**
     * @brief Loads category suggestions into the UI.
     *
     * Typically populates dropdowns or autocomplete hints
     * with existing categories from the database.
     */
    void loadCategoryHints();

    /**
     * @brief Clears all input fields in the dialog.
     *
     * Resets the form to its default empty state.
     */
    void clearFields();
};

#endif // ADDBOOKS_H
