#ifndef ADDSTUDENTS_H
#define ADDSTUDENTS_H

#include <QDialog>
#include "database.h"

namespace Ui {
class AddStudents;
}

/**
 * @class AddStudents
 * @brief Dialog window for adding new students to the system.
 *
 * The AddStudents class provides a graphical interface
 * for entering student details and saving them to the database.
 * It handles user interactions such as saving, canceling,
 * and navigating back to the previous view.
 */
class AddStudents : public QDialog
{
    Q_OBJECT

public:

    /**
     * @brief Constructs the AddStudents dialog.
     *
     * @param parent Pointer to the parent widget (default is nullptr).
     */
    explicit AddStudents(QWidget *parent = nullptr);

    /**
     * @brief Destroys the AddStudents dialog.
     *
     * Cleans up allocated UI resources.
     */
    ~AddStudents();

private slots:

    /**
     * @brief Handles the "Go Back" button click event.
     *
     * Closes the dialog and returns to the previous window.
     */
    void on_goBackButton_2_clicked();

    /**
     * @brief Handles the "Save" button click event.
     *
     * Validates the input fields and attempts to store
     * the new student in the database.
     */
    void on_saveButton_2_clicked();

    /**
     * @brief Handles the "Cancel" button click event.
     *
     * Clears input fields or closes the dialog without saving changes.
     */
    void on_cancelButton_2_clicked();

private:

    /**
     * @brief Pointer to the UI components generated by Qt Designer.
     */
    Ui::AddStudents *ui;
};

#endif // ADDSTUDENTS_H
