#ifndef ADMINMENU_H
#define ADMINMENU_H

#include <QMainWindow>
#include "addbooks.h"
#include "database.h"

namespace Ui {
class AdminMenu;
}

/**
 * @class AdminMenu
 * @brief Main window interface for administrator operations.
 *
 * The AdminMenu class provides access to all administrative
 * functionalities of the library management system, including:
 * - Managing books
 * - Managing students
 * - Issuing and returning books
 * - Viewing dashboard statistics
 *
 * It serves as the central navigation hub for administrators.
 */
class AdminMenu : public QMainWindow
{
    Q_OBJECT

public:

    /**
     * @brief Constructs the AdminMenu window.
     *
     * @param parent Pointer to the parent widget (default is nullptr).
     *
     * Initializes the UI and database connection.
     */
    explicit AdminMenu(QWidget *parent = nullptr);

    /**
     * @brief Destroys the AdminMenu window.
     *
     * Cleans up allocated UI resources.
     */
    ~AdminMenu();

    /**
     * @brief Loads and refreshes dashboard statistics.
     *
     * Retrieves statistical data (e.g., total books, students,
     * issued books) and updates the dashboard display.
     */
    void loadDashboardStats();

private slots:

    /**
     * @brief Opens the "Add New Book" dialog.
     */
    void on_actionAdd_new_book_triggered();

    /**
     * @brief Opens the view displaying all books.
     */
    void on_actionView_books_triggered();

    /**
     * @brief Opens the "Add Student" dialog.
     */
    void on_actionAdd_student_triggered();

    /**
     * @brief Opens the view displaying student information.
     */
    void on_actionView_student_information_triggered();

    /**
     * @brief Opens the book issuing interface.
     */
    void on_actionIssue_books_triggered();

    /**
     * @brief Opens the book return interface.
     */
    void on_actionReturn_books_triggered();

    /**
     * @brief Opens the interface for editing student information.
     */
    void on_actionEdit_student_information_triggered();

    /**
     * @brief Handles administrator logout.
     *
     * Closes the current session and returns to the login screen.
     */
    void on_actionLogout_triggered();

private:

    /**
     * @brief Pointer to the UI components generated by Qt Designer.
     */
    Ui::AdminMenu *ui;

    /**
     * @brief Database instance used by the admin menu.
     *
     * Manages the connection and provides access to repositories/services.
     */
    Database db;
};

#endif // ADMINMENU_H
