#ifndef EDITSTUDENTINFORMATION_H
#define EDITSTUDENTINFORMATION_H

#include <QDialog>
#include <QSqlDatabase>

namespace Ui {
class EditStudentInformation;
}

/**
 * @class EditStudentInformation
 * @brief Dialog window for viewing and editing student information.
 *
 * The EditStudentInformation class provides a user interface
 * that allows administrators to:
 * - Search and load students
 * - Select a student from a table
 * - Modify student details
 * - Save updates to the database
 *
 * It manages the currently selected student's ID to ensure
 * proper update operations.
 */
class EditStudentInformation : public QDialog
{
    Q_OBJECT

public:

    /**
     * @brief Constructs the EditStudentInformation dialog.
     *
     * @param parent Pointer to the parent widget (default is nullptr).
     */
    explicit EditStudentInformation(QWidget *parent = nullptr);

    /**
     * @brief Destroys the EditStudentInformation dialog.
     *
     * Cleans up allocated UI resources.
     */
    ~EditStudentInformation();

    /**
     * @brief Handles selection of a student from the table view.
     *
     * @param index Model index corresponding to the selected row.
     *
     * Loads the selected student's data into the input fields
     * and updates the currentStudentId.
     */
    void onStudentSelected(const QModelIndex &index);

private slots:

    /**
     * @brief Loads students into the table based on a name filter.
     *
     * @param name The name or partial name used for filtering students.
     */
    void loadStudents(const QString &name);

    /**
     * @brief Saves changes made to the selected student's information.
     *
     * Updates the database record corresponding to currentStudentId.
     */
    void saveChanges();

    /**
     * @brief Clears all input fields in the form.
     *
     * Resets the form to its default empty state.
     */
    void clearFields();

    /**
     * @brief Handles the "Go Back" button click event.
     *
     * Closes the dialog and returns to the previous view.
     */
    void on_goBackButton_clicked();

    /**
     * @brief Handles the "Clear" button click event.
     *
     * Clears all input fields without saving changes.
     */
    void on_clearButton_clicked();

private:

    /**
     * @brief Pointer to the UI components generated by Qt Designer.
     */
    Ui::EditStudentInformation *ui;

    /**
     * @brief Stores the ID of the currently selected student.
     *
     * Used when saving updates to ensure the correct record is modified.
     */
    int currentStudentId;
};

#endif // EDITSTUDENTINFORMATION_H
