#ifndef ISSUEBOOKS_H
#define ISSUEBOOKS_H

#include <QDialog>

namespace Ui {
class IssueBooks;
}

/**
 * @class IssueBooks
 * @brief Dialog window for issuing books to students.
 *
 * The IssueBooks class provides a user interface that allows
 * administrators to:
 * - Select a student
 * - Select a book
 * - Issue the book
 *
 * It manages helper mappings for student emails and book IDs
 * to simplify UI interactions and autofill related fields.
 */
class IssueBooks : public QDialog
{
    Q_OBJECT

public:

    /**
     * @brief Constructs the IssueBooks dialog.
     *
     * @param parent Pointer to the parent widget (default is nullptr).
     */
    explicit IssueBooks(QWidget *parent = nullptr);

    /**
     * @brief Destroys the IssueBooks dialog.
     *
     * Cleans up allocated UI resources.
     */
    ~IssueBooks();

private slots:

    /**
     * @brief Handles the "Issue Book" button click event.
     *
     * Validates input fields and attempts to issue the selected
     * book to the chosen student.
     */
    void on_issueBookButton_clicked();

    /**
     * @brief Handles the "Cancel" button click event.
     *
     * Clears input fields or closes the dialog without issuing a book.
     */
    void on_cancelButton_clicked();

    /**
     * @brief Handles the "Go Back" button click event.
     *
     * Closes the dialog and returns to the previous view.
     */
    void on_goBackButton_clicked();

private:

    /**
     * @brief Pointer to the UI components generated by Qt Designer.
     */
    Ui::IssueBooks *ui;

    /**
     * @brief Clears all input fields in the dialog.
     */
    void clearFields();

    /**
     * @brief Loads student name hints for auto-completion.
     *
     * Populates internal mappings between student names and emails.
     */
    void loadStudentHints();

    /**
     * @brief Fills the student's email field based on the selected name.
     *
     * @param name The selected student's name.
     */
    void fillStudentEmail(const QString &name);

    /**
     * @brief Loads book title hints for auto-completion.
     *
     * Populates internal mappings between book titles and IDs.
     */
    void loadBookHints();

    /**
     * @brief Fills the book ID field based on the selected title.
     *
     * @param title The selected book title.
     */
    void fillBookId(const QString &title);

    /**
     * @brief Maps student names to their corresponding email addresses.
     */
    QMap<QString, QString> studentEmails;

    /**
     * @brief Maps book titles to their corresponding book IDs.
     */
    QMap<QString, int> bookIds;
};

#endif // ISSUEBOOKS_H
