#ifndef LOGINWINDOW_H
#define LOGINWINDOW_H

#include <QDialog>
#include "database.h"
#include "ui_loginwindow.h"

namespace Ui {
class LoginWindow;
}

/**
 * @class LoginWindow
 * @brief Dialog window responsible for user authentication.
 *
 * The LoginWindow class provides the graphical interface
 * for user login. It allows users to:
 * - Enter username and password
 * - Toggle password visibility
 * - Attempt authentication
 *
 * Upon successful authentication, it emits a signal containing
 * the user's role to allow role-based navigation.
 */
class LoginWindow : public QDialog {
    Q_OBJECT

public:

    /**
     * @brief Constructs the LoginWindow dialog.
     *
     * @param parent Pointer to the parent widget (default is nullptr).
     */
    explicit LoginWindow(QWidget *parent = nullptr);

    /**
     * @brief Destroys the LoginWindow dialog.
     *
     * Cleans up allocated UI resources.
     */
    ~LoginWindow();

private slots:

    /**
     * @brief Handles the "Login" button click event.
     *
     * Validates user input and attempts authentication.
     * Emits loginSuccessful() if credentials are valid.
     */
    void on_loginButton_clicked();

    /**
     * @brief Handles the password visibility checkbox state change.
     *
     * @param state The new state of the checkbox.
     *
     * Toggles the password field between hidden and visible modes.
     */
    void on_showPasswordCheckBox_stateChanged(int state);

    /**
     * @brief Handles the "Go Back" button click event.
     *
     * Closes the login dialog and returns to the previous window.
     */
    void on_goBackButton_clicked();

signals:

    /**
     * @brief Emitted when login succeeds.
     *
     * @param role The role of the authenticated user (e.g., "admin", "student").
     *
     * Used to redirect the user to the appropriate interface.
     */
    void loginSuccessful(const QString &role);

private:

    /**
     * @brief Pointer to the UI components generated by Qt Designer.
     */
    Ui::LoginWindow *ui;
};

#endif // LOGINWINDOW_H
