#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include "database.h"
#include "adminmenu.h"

QT_BEGIN_NAMESPACE
namespace Ui { class MainWindow; }
QT_END_NAMESPACE

/**
 * @class MainWindow
 * @brief Entry point window of the application.
 *
 * The MainWindow class serves as the initial interface of the
 * library management system. It provides options for:
 * - Logging in
 * - Signing up
 *
 * It manages the primary database connection and handles
 * navigation to role-specific interfaces after successful login.
 */
class MainWindow : public QMainWindow {
    Q_OBJECT

public:

    /**
     * @brief Constructs the MainWindow.
     *
     * @param parent Pointer to the parent widget (default is nullptr).
     *
     * Initializes the UI and database connection.
     */
    MainWindow(QWidget *parent = nullptr);

    /**
     * @brief Destroys the MainWindow.
     *
     * Cleans up allocated UI resources and closes database connection if needed.
     */
    ~MainWindow();

private slots:

    /**
     * @brief Handles the login option button click.
     *
     * Opens the login dialog window.
     */
    void on_loginOptionButton_clicked();

    /**
     * @brief Handles the signup option button click.
     *
     * Opens the registration dialog window.
     */
    void on_signupOptionButton_clicked();

    /**
     * @brief Handles successful user login.
     *
     * @param role The role of the authenticated user (e.g., "admin", "student").
     *
     * Redirects the user to the appropriate interface
     * based on their role.
     */
    void onUserLoggedIn(const QString &role);

private:

    /**
     * @brief Pointer to the UI components generated by Qt Designer.
     */
    Ui::MainWindow *ui;

    /**
     * @brief Database instance used throughout the application.
     */
    Database db;
};

#endif // MAINWINDOW_H
