#ifndef RETURNBOOKS_H
#define RETURNBOOKS_H

#include <QDialog>
#include <QTimer>
#include <QModelIndex>

namespace Ui {
class ReturnBooks;
}

/**
 * @class ReturnBooks
 * @brief Dialog window for processing book returns.
 *
 * The ReturnBooks class provides a user interface that allows:
 * - Searching transactions by student name
 * - Selecting a transaction from a table
 * - Returning issued books
 *
 * It may use a timer to optimize search operations (e.g., delayed search while typing).
 */
class ReturnBooks : public QDialog
{
    Q_OBJECT

public:

    /**
     * @brief Constructs the ReturnBooks dialog.
     *
     * @param parent Pointer to the parent widget (default is nullptr).
     */
    explicit ReturnBooks(QWidget *parent = nullptr);

    /**
     * @brief Destroys the ReturnBooks dialog.
     *
     * Cleans up allocated UI resources.
     */
    ~ReturnBooks();

private slots:

    /**
     * @brief Handles the "Go Back" button click event.
     *
     * Closes the dialog and returns to the previous view.
     */
    void on_goBackButton_5_clicked();

    /**
     * @brief Loads transactions filtered by student name.
     *
     * @param name The name or partial name of the student.
     *
     * Updates the table to display relevant transactions.
     */
    virtual void loadTransactionsByStudent(const QString &name);

    /**
     * @brief Handles selection of a transaction from the table.
     *
     * @param index Model index corresponding to the selected row.
     *
     * Loads the selected transaction details into the form fields.
     */
    virtual void onTransactionSelected(const QModelIndex &index);

    /**
     * @brief Handles the "Return" button click event.
     *
     * Marks the selected transaction as returned
     * and updates the system accordingly.
     */
    void onReturnClicked();

    /**
     * @brief Clears all input fields and selections.
     *
     * Resets the form to its default state.
     */
    void clearFields();

private:

    /**
     * @brief Pointer to the UI components generated by Qt Designer.
     */
    Ui::ReturnBooks *ui;

    /**
     * @brief Timer used to delay search execution.
     *
     * Helps prevent excessive database queries while typing.
     */
    QTimer *searchTimer;

    /**
     * @brief Sets up auto-completion for student name input.
     *
     * Configures suggestions to improve user experience.
     */
    void setupAutocompleter();
};

#endif // RETURNBOOKS_H
