#ifndef SIGNUPWINDOW_H
#define SIGNUPWINDOW_H

#include <QDialog>
#include "database.h"

namespace Ui {
class SignupWindow;
}

/**
 * @class SignupWindow
 * @brief Dialog window for student account registration.
 *
 * The SignupWindow class provides a graphical interface
 * that allows existing students to create user accounts.
 * It handles input validation, password visibility toggling,
 * and emits a signal upon successful registration.
 */
class SignupWindow : public QDialog
{
    Q_OBJECT

public:

    /**
     * @brief Constructs the SignupWindow dialog.
     *
     * @param parent Pointer to the parent widget (default is nullptr).
     */
    explicit SignupWindow(QWidget *parent = nullptr);

    /**
     * @brief Destroys the SignupWindow dialog.
     *
     * Cleans up allocated UI resources.
     */
    ~SignupWindow();

signals:

    /**
     * @brief Emitted when signup is successful.
     *
     * @param role The role assigned to the newly created user.
     *
     * Typically emits "student" after successful registration.
     */
    void signupSuccessful(QString role);  // always "student"

private slots:

    /**
     * @brief Handles the "Sign Up" button click event.
     *
     * Validates input fields and attempts to register the user.
     * Emits signupSuccessful() if registration succeeds.
     */
    void on_signupButton_clicked();

    /**
     * @brief Handles the password visibility checkbox state change.
     *
     * @param state The new state of the checkbox.
     *
     * Toggles the password field between hidden and visible modes.
     */
    void on_showPasswordCheckBox_stateChanged(int state);

    /**
     * @brief Handles the "Go Back" button click event.
     *
     * Closes the dialog and returns to the previous window.
     */
    void on_goBackButton_clicked();

private:

    /**
     * @brief Pointer to the UI components generated by Qt Designer.
     */
    Ui::SignupWindow *ui;
};

#endif // SIGNUPWINDOW_H
