#ifndef STUDENTMENU_H
#define STUDENTMENU_H

#include <QMainWindow>

namespace Ui {
class StudentMenu;
}

/**
 * @class StudentMenu
 * @brief Main window interface for student users.
 *
 * The StudentMenu class provides access to student-specific
 * functionalities within the library management system, such as:
 * - Viewing available books
 * - Logging out of the system
 *
 * It customizes the main window behavior and appearance
 * for student interactions.
 */
class StudentMenu : public QMainWindow
{
    Q_OBJECT

public:

    /**
     * @brief Constructs the StudentMenu window.
     *
     * @param parent Pointer to the parent widget (default is nullptr).
     */
    explicit StudentMenu(QWidget *parent = nullptr);

    /**
     * @brief Destroys the StudentMenu window.
     *
     * Cleans up allocated UI resources.
     */
    ~StudentMenu();

private slots:

    /**
     * @brief Handles the logout action trigger.
     *
     * Ends the current session and returns the user
     * to the login or main screen.
     */
    void on_actionLogout_triggered();

    /**
     * @brief Handles the "View Books" action trigger.
     *
     * Opens a dialog or view displaying available books.
     */
    void on_actionView_books_triggered();

    /**
     * @brief Paint event override.
     *
     * @param event Pointer to the paint event.
     *
     * Allows custom drawing or styling of the main window.
     */
    void paintEvent(QPaintEvent *event);

private:

    /**
     * @brief Pointer to the UI components generated by Qt Designer.
     */
    Ui::StudentMenu *ui;
};

#endif // STUDENTMENU_H
