#ifndef VIEWSTUDENTINFORMATION_H
#define VIEWSTUDENTINFORMATION_H

#include <QDialog>
#include <QSqlTableModel>

namespace Ui {
class ViewStudentInformation;
}

/**
 * @class ViewStudentInformation
 * @brief Dialog window for displaying student information.
 *
 * The ViewStudentInformation class provides an interface
 * for viewing student records stored in the database.
 * It uses a QSqlTableModel to display data in a table view
 * and supports refreshing and filtering functionality.
 */
class ViewStudentInformation : public QDialog
{
    Q_OBJECT

public:

    /**
     * @brief Constructs the ViewStudentInformation dialog.
     *
     * @param parent Pointer to the parent widget (default is nullptr).
     */
    explicit ViewStudentInformation(QWidget *parent = nullptr);

    /**
     * @brief Destroys the ViewStudentInformation dialog.
     *
     * Cleans up allocated UI resources and model memory.
     */
    ~ViewStudentInformation();

private slots:

    /**
     * @brief Handles the "Refresh" button click event.
     *
     * Reloads student data from the database and updates the table view.
     */
    void on_refreshButton_clicked();

    /**
     * @brief Handles the "Go Back" button click event.
     *
     * Closes the dialog and returns to the previous window.
     */
    void on_goBackButton_clicked();

private:

    /**
     * @brief Pointer to the UI components generated by Qt Designer.
     */
    Ui::ViewStudentInformation *ui;

    /**
     * @brief Model used to display student records.
     */
    QSqlTableModel *model;

    /**
     * @brief Loads student data into the table model.
     *
     * @param filter Optional filter string used to restrict displayed records.
     *
     * Applies the filter (if provided) and refreshes the model data.
     */
    void loadStudentData(const QString &filter = QString());
};

#endif // VIEWSTUDENTINFORMATION_H
