#ifndef VIEWBOOKSSTUDENT_H
#define VIEWBOOKSSTUDENT_H

#include "basebookview.h" // Inherit shared logic

namespace Ui {
class ViewBooksStudent;
}

/**
 * @class ViewBooksStudent
 * @brief Dialog window for viewing and searching books (Student view).
 *
 * The ViewBooksStudent class extends BaseBookView and provides
 * student-specific navigation behavior and UI interactions.
 *
 * It reuses the shared table model, filtering logic, and table
 * configuration implemented in BaseBookView while defining
 * custom back-navigation logic appropriate for student users.
 */
class ViewBooksStudent : public BaseBookView
{
    Q_OBJECT

public:

    /**
     * @brief Constructs the ViewBooksStudent dialog.
     *
     * @param parent Pointer to the parent widget (default is nullptr).
     */
    explicit ViewBooksStudent(QWidget *parent = nullptr);

    /**
     * @brief Destroys the ViewBooksStudent dialog.
     *
     * Cleans up allocated UI resources.
     */
    ~ViewBooksStudent();

protected:

    /**
     * @brief Handles student-specific back navigation.
     *
     * Overrides the pure virtual method from BaseBookView
     * to define navigation behavior when returning to
     * the student menu.
     */
    void onGoBack() override;

private slots:

    /**
     * @brief Handles the "Go Back" button click event.
     *
     * Calls the overridden onGoBack() method.
     */
    void on_goBackButton_clicked();

    /**
     * @brief Handles the "Search" button click event.
     *
     * Collects filtering parameters from the UI and applies
     * them using the shared filtering logic in BaseBookView.
     */
    void on_searchButton_clicked();

    /**
     * @brief Handles the "Clear" button click event.
     *
     * Resets search fields and removes any applied filters.
     */
    void on_clearButton_clicked();

private:

    /**
     * @brief Pointer to the UI components generated by Qt Designer.
     */
    Ui::ViewBooksStudent *ui;

    /*
     * Note:
     * The table model and book-loading logic are inherited
     * from BaseBookView to avoid duplication.
     */
};

#endif // VIEWBOOKSSTUDENT_H
