#ifndef VIEWBOOKS_H
#define VIEWBOOKS_H

#include "basebookview.h" // Inherit logic from the base class

namespace Ui {
class ViewBooks;
}

/**
 * @class ViewBooks
 * @brief Dialog window for viewing and searching books (Administrator view).
 *
 * The ViewBooks class extends BaseBookView and provides
 * administrator-specific navigation and UI interactions.
 *
 * It reuses the shared table model, filtering logic, and appearance
 * configuration from BaseBookView, while implementing custom
 * behavior for navigation and user actions.
 */
class ViewBooks : public BaseBookView
{
    Q_OBJECT

public:

    /**
     * @brief Constructs the ViewBooks dialog.
     *
     * @param parent Pointer to the parent widget (default is nullptr).
     */
    explicit ViewBooks(QWidget *parent = nullptr);

    /**
     * @brief Destroys the ViewBooks dialog.
     *
     * Cleans up allocated UI resources.
     */
    ~ViewBooks();

protected:

    /**
     * @brief Handles administrator-specific back navigation.
     *
     * Overrides the pure virtual function from BaseBookView
     * to define custom behavior when returning to the previous screen.
     */
    void onGoBack() override;

private slots:

    /**
     * @brief Handles the "Go Back" button click event.
     *
     * Calls the overridden onGoBack() method.
     */
    void on_goBackButton_clicked();

    /**
     * @brief Handles the "Search" button click event.
     *
     * Collects filter parameters from the UI and applies
     * them using BaseBookView filtering logic.
     */
    void on_searchButton_clicked();

    /**
     * @brief Handles the "Clear" button click event.
     *
     * Resets all search fields and removes applied filters.
     */
    void on_clearButton_clicked();

private:

    /**
     * @brief Pointer to the UI components generated by Qt Designer.
     */
    Ui::ViewBooks *ui;

    /*
     * Note:
     * The model pointer and book loading logic are inherited
     * from BaseBookView to avoid duplication.
     */
};

#endif // VIEWBOOKS_H
